version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chatapp
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.0-alpine
    container_name: my-redis
    command: redis-server --requirepass yourstrong_redispassword --user yourredisusername on >yourstrong_redispassword ~* +@all
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  my_postgres_data:
  redis-data:
